### PR TITLE
implementation of archive options

### PR DESCRIPTION
**Pull request by gasystarttask**
@rdagumampan  manually tested through all supported platform.

### CODE REVIEW

**Comment by gasystarttask** [comment]
resolve conflict [wip]

**Comment by rdagumampan** [comment]
Hi @gasystarttask ,

Thanks for your contribution. Dont worry about conflict i will have to do manual merge on this PR I think.

Have a nice weekend!

Br, Rodel

**Comment by gasystarttask** [comment]
> Hi @gasystarttask ,
> 
> Thanks for your contribution. Dont worry about conflict i will have to do manual merge on this PR I think.
> 
> Have a nice weekend!
> 
> Br, Rodel
@rdagumampan 
You're welcome.

Notice that my modification is based on the older version, that's why I've these conflicts.

Thanks,

**Comment by rdagumampan** [comment]
@gasystarttask ,

Again thanks for this valuable contribution to yuniql capability. I have merged the changes now and will do some refactoring. I hope you dont mind me changing couple of things around. Notably,
- I think I we dont need this `dataService.GetSqlForGetAllVersionAsJson` because we can serialize the results of GetAllVersions into JSON using native JSON serializer in .NET Core 3.1? Unless I missed your intent on for creating this.
- For consistently, we should always use `var` when declaring fields. I'm still learning this so I am documenting some of these coding guidelines for everyone :)
- On `migrationService.ResetVersion` we have split the implementation into two now `MigrationService` and `NonTransactionalMigrationService`. This allows use to remove this line `if(_dataService.IsAtomicDDLSupported)` which I think much neater.

**Comment by rdagumampan** [comment]
@gasystarttask I had to revert the merge and wait for your input first. I like the fact you are able to follow the patterns on where to make the change. Extending the `IDataService` to serve compatible SQL is the right way to go 👍 

Noted here extra review comments:
- The logic for finding version folders are abstracted in `DirectoryService`. `IDirectoryService` is injected into MigrationService so we can perform unit testing. Calling `Directory` directly would make it impossible to mock in unit tests.
- I realized, we also need to validate if the local list of versions if it matches with the data from DB. It could be that its because the local repo is outdated and user mistakenly rebased the Db with missing folder.

Would you have time to tune up the code and make another PR? :) This is already a working solution and if your time can;t permit, I can pickup from here and you can resync your fork.

Again thanks for working on this. 

Cheers, Rodel

**Comment by rdagumampan** [comment]
Here's an example of serializing objects in .NET Core
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to

**Comment by gasystarttask** [comment]
Hello @rdagumampan 
Thanks for the review and your feedback.
It's my pleasure to have contributed to this project. 
OK, I try to tune up the code in this week and I will make another PR.

Regards,
Rivo

**Pull request merged**
