### PR TITLE
#110: Implemented --no-transaction switch for Run command

### PR DESCRIPTION
**Pull request by Jabestrada**

### CODE REVIEW

**Comment by rdagumampan** [comment]
@Jabestrada  thanks for PR, I will review and merge them this week. This may fall into v1.1 as it maybe relatively significant change.

Btw, I think you know yuniql very well by now. Feel free to pick on more advanced cases. I am currently working on support for Snowflake DB. I also look forward to support Azure Synapse Analytics and Amazon Redshift next. You may want to explore those platforms.

Br, Rodel

**Comment by Jabestrada** [comment]
I tried looking at both Synapse Analytics and Redshift but I think both do not have free plans?

**Comment by rdagumampan** [comment]
Hi @Jabestrada, sorry for late reply... been really hectic week at work. Yes, you are right there are no free tier on these platforms. For Synapse Analytics, I think Azure Trial Credits can be used here if you are interested.

Or.. you can try with SqlLite first. I think its relatively easy to implement this.
https://github.com/rdagumampan/yuniql/issues/109

**Comment by Jabestrada** [comment]
Hey, no worries. Had a busy week myself. I have a long-standing Azure account so I guess I don't qualify for trial (?). I'll have a look at SqlLite instead for now.

**Comment by rdagumampan** [comment]
Closed by mistake as I decided to delete the dev branch.
Can you make a PR again to master. Thanks!

**Comment by Jabestrada** [comment]
Do you still need a new PR to master? Seems like this has been merged to master already.

**Comment by rdagumampan** [comment]
Yes, it has been merged already :)

**Pull request merged**
