### PR TITLE
Dotnet 6 upgrade

### PR DESCRIPTION
**Pull request by Jean-Paul76**
Upgrade to .Net 6.0 and bump referenced assemblies to their latest stable versions.

I'm running on POP_OS 22.04, and as such added bash files for kicking off the tests. Only the SQL Server version was tested thus far however.

The project builds, and running the MSSQL Server suit of tests had only 7 failures. I'm not sure if this is due to my environment or something else. If someone could check for me that would be much appreciated.

### CODE REVIEW

**Comment by rdagumampan** [comment]
Thanks for this. I started looking at it and will run some tests. Hit a wall, there must be some file encoding or path corruption around that blocks me from checking out the branch or PR branch. 

image

**Comment by Jean-Paul76** [comment]
Thx, not sure what happened there. I'll have a look today or tomorrow.

Kind regards

Jean-Paul Malherbe
082 3099 609

**Comment by Jean-Paul76** [comment]
Since I checked in from Linux this seems relevant.

https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/

**Comment by Jean-Paul76** [comment]
I'm planning on redoing that branch on a Windows machine. Should be quicker than trying to resolve the problem in the broken branch.

Kind regards

Jean-Paul Malherbe
082 3099 609

**Comment by Jean-Paul76** [comment]
Closing this Pull Request because of the file-path issue. Replaced by https://github.com/rdagumampan/yuniql/pull/266

**Pull request closed without merging**
