### PR TITLE
Issue 223 Upgrade to .Net 6.0 LTS

### PR DESCRIPTION
**Pull request by Jean-Paul76**
Upgraded all projects to use .net 6 and updated all referenced assemblies to their latest versions.

I ran the SQL Server test, 9 of which failed.
Test Result

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test_Run_Fail_Migration_When_Version_Directory_With_Explicit_Transaction_Has_Other_Directories
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Fail_Migration_When_Version_With_Explicit_Transaction_Directory_Has_Files
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Fail_Migration_When_DDL_Failed_And_Transactional_DDL_Not_Supported
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Fail_Migration_When_No_Force_Continue_After_Failue_Option_Enabled
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Ok_Migration_With_Force_Continue_After_Failue_Option_Enabled
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Ok_Without_Explicit_Transaction
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Ok_With_Explicit_Transaction
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Ok_Without_Explicit_Transaction_With_SubDirectories
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.

  Failed Test_Run_Ok_With_Explicit_Transaction_With_SubDirectories
  Standard Output Messages:
 Target database platform or version does not support atomic DDL operations. DDL operations like CREATE TABLE, CREATE VIEW are not gauranteed to be executed transactional.
```

### CODE REVIEW

**Comment by rdagumampan** [comment]
@Jean-Paul76 , thanks for new PR with fix to git issues. I was able to build and reproduce those failed tests now. It seems that net6 sdk still consider these tests as failed even if it should be ignored. I will investigate further and let you know later today.

image

**Comment by rdagumampan** [comment]
I made small changes to fix the custom `TestMethodEx` attribute and tests have passed. I have not run tests for Snowflake and Redshift but I will run during release as I need to setup a new instance every time. I will push my changes to this PR and merge it. Thanks for excellent work. This has been major ticket I was hoping to sit down during Easter but I was not able to get the time :)

##### SQL Server
image

```
#### PostgresSql
Passed!  - Failed:     0, Passed:   202, Skipped:    16, Total:   218, Duration: 4 m 9 s - Yuniql.PlatformTests.dll (net6.0)
dc
#### MySql
Passed!  - Failed:     0, Passed:   192, Skipped:    26, Total:   218, Duration: 9 m 8 s - Yuniql.PlatformTests.dll (net6.0)

#### MariaDB
Passed!  - Failed:     0, Passed:   192, Skipped:    26, Total:   218, Duration: 6 m 45 s - Yuniql.PlatformTests.dll (net6.0)

#### Oracle
Passed!  - Failed:     0, Passed:   190, Skipped:    28, Total:   218, Duration: 13 m 38 s - Yuniql.PlatformTests.dll (net6.0)
```

**Review by rdagumampan — APPROVED** [review]
Great work. Really appreciate your effort in lifting yuniql to .NET 6 LTS!

**Comment by Jean-Paul76** [comment]
That is awesome news, thank you for the update.

**Pull request merged**
